### ISSUE TITLE
Data issue 

### ISSUE THREAD

**Issue by OdinZhang** [terraytherapeutics/COATI#8]
Dear sir, 

This is an excellent work! I appreciate your efforts and dedication.

However, I encountered an issue while running the train.py script. It seems to generate an error, as shown in the linked screenshot: 

![data_error](https://github.com/terraytherapeutics/COATI/assets/106578915/d1fd09c9-9254-4752-8fc9-a1bbe7e4fab3)

Could you please assist me in resolving this problem? Alternatively, could you provide a quick training example using some molecules to help me better understand how the code operates?

Thanks! 

Best regards,
Odin

**Comment by ecwterray** [comment]
Hello! Can you send a full stack trace? My guess is that it's trying to load an artifact or save something from an S3 bucket that you don't have access to...
